### ISSUE TITLE
Fix the theming to be compatible with Mkdocs 1.4.2

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apk#58]
**Description:**

- [x] Fix the theming to be compatible with [Mkdocs 1.4.2](https://github.com/mkdocs/mkdocs/releases)
- [x] Fix the doc search to be compatible with Mkdocs 1.4.2
- [x] Look at using Mkdocs 1.4.2 with Python 3.11 (preferable) or 3.9

Summary of issues based on the docs in dev-apk

- [x] https://github.com/wso2/docs-apk/issues/114

**Comment by chanaka3d** [comment]
Notes on the tasks in the list.
Fix the theming to be compatible with [Mkdocs 1.4.2]. this can be marked as done since the main part of the theming is done. We can treat other minor issues like tabs not rendered etc as separate tasks.
 Fix the doc search to be compatible with Mkdocs 1.4.2. This is done and the separate Jenkins build is also running smoothly.
 Look at using Mkdocs 1.4.2 with Python 3.11 (preferable) or 3.9. We went with Python 3.10 and the Readme is also updated accordingly.

**Comment by chanaka3d** [comment]
All the items listed here are fixed. Please check and confirm in the dev environment.
